// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {audio} from '../models';
import {dict} from '../models';
import {pinyin} from '../models';

export function AddCustomWord(arg1:string,arg2:string,arg3:number):Promise<void>;

export function CancelRecording():Promise<void>;

export function CheckFirstRun():Promise<boolean>;

export function ClearPinyinBuf():Promise<void>;

export function CloseSettings():Promise<void>;

export function CommitCandidate(arg1:string):Promise<void>;

export function CompleteGuide():Promise<void>;

export function GetASRMode():Promise<string>;

export function GetAllConfig():Promise<string>;

export function GetAppState():Promise<string>;

export function GetAudioDevices():Promise<Array<audio.Device>>;

export function GetConfig(arg1:string):Promise<string>;

export function GetDictStats():Promise<dict.Stats>;

export function GetHotkey():Promise<string>;

export function GetInputMode():Promise<string>;

export function GetPinyinBuf():Promise<string>;

export function GetVersion():Promise<string>;

export function GetVolume():Promise<number>;

export function GetXunfeiCredentials():Promise<Record<string, string>>;

export function HasXunfeiCredentials():Promise<boolean>;

export function ImportDict(arg1:string):Promise<number>;

export function IsRecording():Promise<boolean>;

export function MinimizeToTray():Promise<void>;

export function ProcessKey(arg1:string):Promise<pinyin.CandidateResult>;

export function ResetConfig():Promise<void>;

export function SelectCandidate(arg1:number):Promise<string>;

export function SetASRMode(arg1:string):Promise<void>;

export function SetAudioDevice(arg1:string):Promise<void>;

export function SetConfig(arg1:string,arg2:string):Promise<void>;

export function SetHotkey(arg1:string):Promise<void>;

export function SetXunfeiCredentials(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function StartRecording():Promise<void>;

export function StopRecording():Promise<void>;
