// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCustomWord(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddCustomWord'](arg1, arg2, arg3);
}

export function CancelRecording() {
  return window['go']['main']['App']['CancelRecording']();
}

export function CheckFirstRun() {
  return window['go']['main']['App']['CheckFirstRun']();
}

export function ClearPinyinBuf() {
  return window['go']['main']['App']['ClearPinyinBuf']();
}

export function CloseSettings() {
  return window['go']['main']['App']['CloseSettings']();
}

export function CommitCandidate(arg1) {
  return window['go']['main']['App']['CommitCandidate'](arg1);
}

export function CompleteGuide() {
  return window['go']['main']['App']['CompleteGuide']();
}

export function GetASRMode() {
  return window['go']['main']['App']['GetASRMode']();
}

export function GetAllConfig() {
  return window['go']['main']['App']['GetAllConfig']();
}

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']();
}

export function GetAudioDevices() {
  return window['go']['main']['App']['GetAudioDevices']();
}

export function GetConfig(arg1) {
  return window['go']['main']['App']['GetConfig'](arg1);
}

export function GetDictStats() {
  return window['go']['main']['App']['GetDictStats']();
}

export function GetHotkey() {
  return window['go']['main']['App']['GetHotkey']();
}

export function GetInputMode() {
  return window['go']['main']['App']['GetInputMode']();
}

export function GetPinyinBuf() {
  return window['go']['main']['App']['GetPinyinBuf']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetVolume() {
  return window['go']['main']['App']['GetVolume']();
}

export function GetXunfeiCredentials() {
  return window['go']['main']['App']['GetXunfeiCredentials']();
}

export function HasXunfeiCredentials() {
  return window['go']['main']['App']['HasXunfeiCredentials']();
}

export function ImportDict(arg1) {
  return window['go']['main']['App']['ImportDict'](arg1);
}

export function IsRecording() {
  return window['go']['main']['App']['IsRecording']();
}

export function MinimizeToTray() {
  return window['go']['main']['App']['MinimizeToTray']();
}

export function ProcessKey(arg1) {
  return window['go']['main']['App']['ProcessKey'](arg1);
}

export function ResetConfig() {
  return window['go']['main']['App']['ResetConfig']();
}

export function SelectCandidate(arg1) {
  return window['go']['main']['App']['SelectCandidate'](arg1);
}

export function SetASRMode(arg1) {
  return window['go']['main']['App']['SetASRMode'](arg1);
}

export function SetAudioDevice(arg1) {
  return window['go']['main']['App']['SetAudioDevice'](arg1);
}

export function SetConfig(arg1, arg2) {
  return window['go']['main']['App']['SetConfig'](arg1, arg2);
}

export function SetHotkey(arg1) {
  return window['go']['main']['App']['SetHotkey'](arg1);
}

export function SetXunfeiCredentials(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetXunfeiCredentials'](arg1, arg2, arg3);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartRecording() {
  return window['go']['main']['App']['StartRecording']();
}

export function StopRecording() {
  return window['go']['main']['App']['StopRecording']();
}
